version     = "0.1.0"
author      = "Softmax"
description = "One cog, five partially observed 13x13 gridworld tasks, and a sentence telling it what to do."
license     = "MIT"

srcDir = "src"

requires "nim >= 2.2.4"
requires "bitworld >= 0.1.0"
requires "pixie"
requires "mummy >= 0.4.7"
requires "curly >= 1.1.1"
requires "supersnappy >= 2.1.3"
requires "flatty >= 0.3.4"
requires "zippy"
requires "jsony"
